// ===========================================================================
// Firebase Configuration Placeholder
// ===========================================================================
//
// This file exists to document the Firebase setup steps. The actual
// firebase_options.dart is generated by FlutterFire CLI and should NOT be
// committed to version control (it contains project-specific API keys).
//
// ---------------------------------------------------------------------------
// SETUP INSTRUCTIONS
// ---------------------------------------------------------------------------
//
// 1. Install the FlutterFire CLI (one-time):
//      dart pub global activate flutterfire_cli
//
// 2. Ensure you are logged in to Firebase:
//      firebase login
//
// 3. From the customer_app/ directory, run:
//      flutterfire configure \
//        --project=<your-firebase-project-id> \
//        --platforms=android,ios \
//        --android-package-name=com.alhai.customer \
//        --ios-bundle-id=com.alhai.customer
//
//    This will:
//      a) Create/download google-services.json -> android/app/
//      b) Create/download GoogleService-Info.plist -> ios/Runner/
//      c) Generate lib/firebase_options.dart
//
// 4. (Optional) If you want to pass FirebaseOptions explicitly, update
//    main.dart to use:
//
//      import 'firebase_options.dart';
//      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
//
//    The current setup uses Firebase.initializeApp() WITHOUT explicit options,
//    which relies on the native config files (google-services.json /
//    GoogleService-Info.plist) being present. Both approaches work.
//
// 5. Verify .gitignore includes:
//      google-services.json
//      GoogleService-Info.plist
//      lib/firebase_options.dart
//
// ---------------------------------------------------------------------------
// IMPORTANT: Bundle ID must be com.alhai.customer on BOTH platforms.
// ---------------------------------------------------------------------------
