// =========================================================================
// PLACEHOLDER -- replace with the real file generated by FlutterFire CLI.
//
// Steps:
//   1. Install the FlutterFire CLI:
//        dart pub global activate flutterfire_cli
//
//   2. From the driver_app/ directory, run:
//        flutterfire configure --project=<your-firebase-project-id>
//
//   3. The CLI will generate a real firebase_options.dart with your
//      project's API keys.  It will also place google-services.json
//      (Android) and GoogleService-Info.plist (iOS) in the correct
//      native directories.
//
//   4. Delete this placeholder once the real file exists.
// =========================================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '${defaultTargetPlatform.name}. '
          'Run `flutterfire configure` to generate firebase_options.dart.',
        );
    }
  }

  // TODO: Replace these placeholder values with real Firebase config.
  // These are intentionally invalid and will cause Firebase.initializeApp()
  // to fail until you run `flutterfire configure`.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER-run-flutterfire-configure',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'placeholder-project',
    storageBucket: 'placeholder-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER-run-flutterfire-configure',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'placeholder-project',
    storageBucket: 'placeholder-project.appspot.com',
    iosBundleId: 'com.alhai.driverApp',
  );
}
