include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    sort_constructors_first: ignore
    sort_child_properties_last: ignore
    null_check_on_nullable_type_parameter: ignore

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: false
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: false
